export const latestPriceCardStyles = {
  card: "h-full shadow-sm",
  header: "flex flex-row items-start justify-between space-y-0",
  title: "text-lg",
  description: "mt-1 text-sm",
  iconWrapper: "rounded-full p-2",
  content: "space-y-6",
  highlightBox: "rounded-2xl border p-5",
  highlightLabel: "text-sm font-medium",
  highlightValue: "mt-2 text-4xl font-bold tracking-tight",
  highlightDate: "mt-3 text-sm",
  statsGrid: "grid grid-cols-2 gap-4",
  statItem: "rounded-xl border p-4",
  statLabel: "text-xs font-medium uppercase tracking-wide",
  statValue: "mt-2 text-sm font-semibold",
};
